- dbtwiz/build.py
When running build with `--save-state`, copy `target/run_results.json` to bucket too, so we can use this to analyze time spent per model and possibly other fun things.
> Save run_results.json to bucket in addition to manifest.json.

- dbtwiz/backfill.py
The job name limit is 64 characters. Implement functionality for shortening job name.
The method works by halving the longest word until the total length is short enough. Words are removed if we can no longer halve words.
> Shorten backfill job name

- dbtwiz/manifest.py
Corrected path creation for dbtwiz folder. The current implementation added the manifest name as a folder, rather than just creating the parent folder `.dbtwiz ` as intended.
> Fix: Corrected path creation for dbtwiz folder

- dbtwiz/build.py
- dbtwiz/config.py
- dbtwiz/manifest.py
- setup.py
Fix for issue https://github.com/amedia/dbtwiz/issues/24.
Also, use `{PROJECT_ROOT}/.dbtwiz/prod-state/manifest.json` as path for production manifest.
> Make sure project .dbtwiz directory exists prior to use.

- dbtwiz/commands/__init__.py
- dbtwiz/create/model.py
- dbtwiz/main.py
- dbtwiz/model/__init__.py
- dbtwiz/model/create.py
- dbtwiz/model/inspect.py
- dbtwiz/project.py
- dbtwiz/source/__init__.py
- dbtwiz/source/create.py
- setup.py
- changed to `model create` and `source create` (from `create model` and `create source`)
- refactored commands for consistency, incl. move original model commands as `model inspect`
- materialization was pre-defined as `view` if not provided as parameter, which was incorrect
- the order of questions was changed to make more sense
- if materialization is `view` then frequency is not applicable and is thus skipped
- added check to hinder model prefix being provided with model name input
- corrected typo in message when cancelling
- updated patch version to `0.2.2`
The new order of `dbtwiz` functions is now:
While for `dbtwiz model` it is:
> Refactor: Changed to `model create` and `source create` + corrected bugs

- dbtwiz/commands/__init__.py
#31 introduced a recursive loop issue for commands, where the same function name was imported and defined in the same file. This fixes this issue.
> Fix: Corrected recursive loop issue for commands

- dbtwiz/model/create.py
Corrected marts only questions for model creator. `service_consumers` and `access_policy` are only relevant for `marts` and `bespoke`. However, the filter for this was only applied if the parameter for these parameters was used, and not in general.
> Fix: Corrected marts/bespoke only questions for model creator

- dbtwiz/admin/__init__.py
- dbtwiz/admin/cleanup.py
- dbtwiz/admin/partition.py
- dbtwiz/bigquery.py
- dbtwiz/interact.py
- dbtwiz/manifest.py
- dbtwiz/source/create.py
Added admin submodule for updating mismatched partition expiries.
It uses the production manifest to list tables with partition expiry defined, and compares the defined expiration with the bigquery table definition.
There is one optional argument, `--model-name` / `-m`, that can be provided as a filter:
> Feature: Admin submodule for updating mismatched partition expiries

- dbtwiz/auth.py
When activating `shell=True` for `subprocess` command, providing the command as a sequence of arguments no longer work and the command must be a single string.
> Fix: Corrected the subprocess command when using shell

- dbtwiz/admin/cleanup.py
- pyproject.toml
Fixed `empty_development_dataset` which was expecting table references, but now get table names from `fetch_tables_in_dataset`.
Bumped version to `0.2.4`.
> fix: fetch_tables_in_dataset returns names, not references

- dbtwiz/dbt/model.py
- dbtwiz/model/validate.py
Correct model name for base path and pattern used to replace fqn with ref/source
> Fix: Correct model name for base path and pattern used to replace fqn with ref/source

- dbtwiz/admin/cleanup.py
- pyproject.toml
There was a bug in the bq query that fetches all tables from the information schema, as you can only query a single project at a time. The query is altered to specify the project for which information schema to use.
> Fix: Corrected bq query when identifying orphaned models across projects

- dbtwiz/gcp/bigquery.py
The IAM policy fix implemented in #54 should also have been added to the function `migrate_table`.
Example bug:
After fix:
> Fix: Corrected IAM policy setting for table migration

- dbtwiz/admin/cleanup.py
- pyproject.toml
The orphaned models cleanup script had two erroneous filters that caused it to not remove contents in datasets that no longer had a match in dbt (e.g. an entire folder was deleted in dbt), plus had a filter removing elementary models from comparison.
> Fix: remove erroneous filters for orphan cleanup

- dbtwiz/commands/backfill.py
Use `shell=True` for `backfill` subprocess command to work in windows
> Fix: use `shell=True` for `backfill` subprocess command to work in windows

- dbtwiz/commands/backfill.py
- pyproject.toml
Passing a list as argument to `subprocess.run` when `shell=True` does not work in Linux, so pass a space-separated string instead.
> Use string instead of list with subprocess.run when shell=True

- README.md
- dbtwiz/gcp/auth.py
- pyproject.toml
Currently when running `backfill` and the user hasn't run `gcloud auth login`, the script will fail with this error message:
>Reauthentication required.
ERROR: (gcloud.auth.print-access-token) There was a problem refreshing your current auth tokens: Reauthentication failed. Reauthentication challenge failed due to API error: NO_AVAILABLE_CHALLENGES
Please run:
>$ gcloud auth login
>to obtain new credentials.
>If you have already logged in with a different account, run:
>to select an already authenticated account to use.
Originally, the script used `gcloud auth list` to identify authenticated users, but this didn't take into consideration whether the authentication token was still valid.
As a result, we now use `gcloud auth print-access-token` to ensure correct token status so that …
> Fix: corrected gcloud auth check

- dbtwiz/model/move.py
When migrating a dbt model, the old sql file is defined as:
```
select * from {{ ref('<new model name>') }}
```
It should, however, be defined like this:
```
select * from {{ ref("<new model name>") }}
```
> Fix: corrected sql format for old model when migrating

- dbtwiz/model/move.py
#69 changed the model reference replacement logic to not take curly braces into consideration, but left out the part where curly braces are added when replacing the model reference. This PR removes the curly brace addition.
> Fix: removed addition of curly braces when replacing model reference

- dbtwiz/gcp/auth.py
The check that identifies whether `gcloud auth login` is required for `backfill` works locally, but not in a codespace.
The cause seems to be that the error message returned is: `You do not currently have an active account selected`
And this isn't one of the error messages that are checked by the code.
> Fix: correct auth issue for backfill that happens in codespaces

- dbtwiz/model/validate.py
- poetry.lock
- pyproject.toml
Handled breaking change in shandy-sqlfmt v0.27.0.
A new positional argument was added to the function `load_config_file` which caused sqlfmt model validation to fail.
> Fix: handled breaking change in shandy-sqlfmt v0.27.0

- poetry.lock
- pyproject.toml
```
Package operations: 1 install, 22 updates, 1 removal
- Removing ordered-set (4.1.0)
- Updating jsonschema-specifications (2025.4.1 -> 2025.9.1)
- Updating markupsafe (3.0.2 -> 3.0.3)
- Installing orderly-set (5.5.0)
- Updating protobuf (6.32.0 -> 6.32.1)
- Updating deepdiff (7.0.1 -> 8.6.1)
- Updating dbt-protos (1.0.348 -> 1.0.375)
- Updating pydantic (2.11.7 -> 2.11.9)
- Updating click (8.2.1 -> 8.3.0)
- Updating more-itertools (10.7.0 -> 10.8.0)
- Updating pyyaml (6.0.2 -> 6.0.3)
- Updating dbt-common (1.28.0 -> 1.32.0)
- Updating wcwidth (0.2.13 -> 0.2.14)
- Updating ruamel-yaml-clib (0.2.12 -> 0.2.14)
- Updating coverage (7.10.5 -> 7.10.7)
- Updating dbt-adapters (1.16.5 -> 1.16.7)
- Updating pytest (8.4.1 -> 8.4.2)
- Updating identify (2.6.13 -> 2.6.14)
- Updating dbt-core …
```
> Upgrade: updated poetry packages
